import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Explicit sidebar for the Shadow IT IT best-practice repository.
 *
 * Structure: an Introduction, then three audience sections (Business Owners,
 * Managed Service Providers, Internal IT Teams), each split into the
 * Strategy / Tactical / Operational tiers. Finally the audience-neutral
 * Technical Library — the canonical layer the Operational pages reference,
 * including a nested Script Repository (Windows + Microsoft 365 workloads).
 *
 * The sidebar is explicit (not autogenerated) so the default Docusaurus
 * tutorial docs are excluded from the menu — they remain reachable by URL but
 * are hidden from navigation. Keep the key named `tutorialSidebar` because the
 * navbar item in docusaurus.config.ts references that sidebarId.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Business Owners',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Business Owners',
        description:
          'For readers accountable to a board or to themselves. Technology framed as a business decision — risk, cost, and continuity, not CVEs.',
        slug: '/business-owners',
      },
      items: [
        'business-owners/strategy',
        'business-owners/tactical',
        'business-owners/operational',
      ],
    },
    {
      type: 'category',
      label: 'Managed Service Providers',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Managed Service Providers',
        description:
          'For readers delivering IT as a service to many clients. Everything framed through multi-tenancy, repeatability, margin, and liability transfer.',
        slug: '/managed-service-providers',
      },
      items: [
        'managed-service-providers/strategy',
        'managed-service-providers/tactical',
        'managed-service-providers/operational',
      ],
    },
    {
      type: 'category',
      label: 'Internal IT Teams',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Internal IT Teams',
        description:
          'For readers who execute and own the outcome for a single organisation. Framed around accountability, depth, and institutional knowledge.',
        slug: '/internal-it-teams',
      },
      items: [
        'internal-it-teams/strategy',
        'internal-it-teams/tactical',
        'internal-it-teams/operational',
      ],
    },
    {
      type: 'category',
      label: 'Technical Library',
      collapsed: true,
      link: {type: 'doc', id: 'technical-library/index'},
      items: [
        'technical-library/mfa-entra-hardening',
        'technical-library/patch-management',
        'technical-library/backup-and-dr',
        'technical-library/essential-eight-baseline',
        {
          type: 'category',
          label: 'Script Repository',
          collapsed: true,
          link: {type: 'doc', id: 'technical-library/script-repository/index'},
          items: [
            'technical-library/script-repository/windows',
            {
              type: 'category',
              label: 'Microsoft 365',
              collapsed: true,
              link: {
                type: 'doc',
                id: 'technical-library/script-repository/microsoft-365/index',
              },
              items: [
                'technical-library/script-repository/microsoft-365/entra',
                'technical-library/script-repository/microsoft-365/exchange-online',
                'technical-library/script-repository/microsoft-365/sharepoint-online',
                'technical-library/script-repository/microsoft-365/onedrive',
                'technical-library/script-repository/microsoft-365/teams',
                'technical-library/script-repository/microsoft-365/intune',
                'technical-library/script-repository/microsoft-365/purview',
                'technical-library/script-repository/microsoft-365/defender',
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
