import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Explicit sidebar for the Shadow IT IT best-practice repository.
 *
 * Structure: an Introduction category (linked to the `intro` doc) containing the
 * three audience sections (Business Owners, Managed Service Providers, Internal
 * IT Teams), each split into the Strategy / Tactical / Operational tiers. Then
 * the audience-neutral Technical Library (canonical baselines/runbooks),
 * followed by the Script Repository — promoted to its own top-level section
 * (Windows + Microsoft 365 workloads).
 *
 * The sidebar is explicit (not autogenerated) so the default Docusaurus
 * tutorial docs are excluded from the menu — they remain reachable by URL but
 * are hidden from navigation. Keep the key named `tutorialSidebar` because the
 * navbar item in docusaurus.config.ts references that sidebarId.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      // Introduction is now a category whose own link is the `intro` doc, with
      // the three audience sections nested beneath it as sub-pages.
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      link: {type: 'doc', id: 'intro'},
      items: [
        {
          type: 'category',
          label: 'Business Owners',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Business Owners',
            description:
              'For readers accountable to a board or to themselves. Technology framed as a business decision — risk, cost, and continuity, not CVEs.',
            slug: '/business-owners',
          },
          items: [
            'business-owners/strategy',
            'business-owners/tactical',
            'business-owners/operational',
          ],
        },
        {
          type: 'category',
          label: 'Managed Service Providers',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Managed Service Providers',
            description:
              'For readers delivering IT as a service to many clients. Everything framed through multi-tenancy, repeatability, margin, and liability transfer.',
            slug: '/managed-service-providers',
          },
          items: [
            'managed-service-providers/strategy',
            'managed-service-providers/tactical',
            'managed-service-providers/operational',
          ],
        },
        {
          type: 'category',
          label: 'Internal IT Teams',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Internal IT Teams',
            description:
              'For readers who execute and own the outcome for a single organisation. Framed around accountability, depth, and institutional knowledge.',
            slug: '/internal-it-teams',
          },
          items: [
            'internal-it-teams/strategy',
            'internal-it-teams/tactical',
            'internal-it-teams/operational',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Technical Library',
      collapsed: true,
      link: {type: 'doc', id: 'technical-library/index'},
      items: [
        'technical-library/mfa-entra-hardening',
        'technical-library/patch-management',
        'technical-library/backup-and-dr',
        'technical-library/essential-eight-baseline',
      ],
    },
    {
      type: 'category',
      label: 'Script Repository',
      collapsed: true,
      link: {type: 'doc', id: 'script-repository/index'},
      items: [
        'script-repository/windows',
        {
          type: 'category',
          label: 'Microsoft 365',
          collapsed: true,
          link: {type: 'doc', id: 'script-repository/microsoft-365/index'},
          items: [
            {
              type: 'category',
              label: 'Entra ID',
              collapsed: true,
              link: {type: 'doc', id: 'script-repository/microsoft-365/entra/index'},
              items: [
                {
                  type: 'category',
                  label: 'Enterprise Applications',
                  collapsed: true,
                  link: {
                    type: 'doc',
                    id: 'script-repository/microsoft-365/entra/enterprise-applications/index',
                  },
                  items: [
                    'script-repository/microsoft-365/entra/enterprise-applications/auditing-stale-enterprise-applications',
                  ],
                },
              ],
            },
            'script-repository/microsoft-365/exchange-online',
            'script-repository/microsoft-365/sharepoint-online',
            'script-repository/microsoft-365/onedrive',
            'script-repository/microsoft-365/teams',
            'script-repository/microsoft-365/intune',
            'script-repository/microsoft-365/purview',
            'script-repository/microsoft-365/defender',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
